[window]
opacity = 0.6
padding = { x = 20, y = 20 }
dynamic_padding = true

# [font]
# normal = { family = "JetBrainsMono Nerd Font" }
# bold = { family = "JetBrainsMono Nerd Font" }
# size = 16.0
# offset.y = 2

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 100
blink_timeout = 0

[terminal]
osc52 = "CopyPaste"

[scrolling]
history = 50000

# [general]
# import = ["~/.config/alacritty/plugins/alabaster_dark.toml"]
